### PR TITLE
Added fix for issue #1472

### LINKED ISSUE #1472: Crash: driver.rb:138  undefined method
**Describe the bug**
Given `vagrant up --provider=libvirt` has been invoked and some (to me unknown) event causes the  vagrant domain to be lost
when I invoke a vagrant command like `vagrant status`
then I get the error message
```
root@a1dfd93e66e1:/# vagrant status
Traceback (most recent call last):
        14: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/bin/vagrant:231:in `<main>'
         ...
         1: from /root/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/provider.rb:98:in `state'
/root/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/driver.rb:138:in `state': undefined method `to_sym' for nil:NilClass (NoMethodError)
```
**Expected behavior**
```
root@a1dfd93e66e1:/# vagrant status
Current machine states:
ubuntu-win10              not created (libvirt)
The Libvirt domain is not created. Run `vagrant up` to create it
```

**Versions:**
- Libvirt version: `vagrant-libvirt (0.7.0, global)`
- Vagrant version [output of `vagrant version`]: `Installed Version: 2.2.19`
  
- Vagrant flavour [Upstream or Distro]: `https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_x86_64.deb`
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:
   - `vagrant-libvirt (0.7.0, global)` 

**Additional info**
This issue is not about the root cause of why the domain is lost.
This issue only focuses on a missing check in `.../lib/vagrant-libvirt/driver.rb:138`
The line is currently 
   `return :not_created if domain.nil? || domain.state.to_sym == :terminated`
but I propose that is should be
   `return :not_created if domain.nil? || domain.state.nil? || domain.state.to_sym == :terminated`

I am currently working around the issue by patching my vagrant installation:
```
root@a1dfd93e66e1:/# F='/root/.vagrant.d//gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/driver.rb'
root@a1dfd93e66e1:/# sed -i '138s/^.*$/        return :not_created if domain.nil? || domain.state.nil? || domain.state.to_sym == :terminated/' "${F}"
```

### PR DESCRIPTION
**Pull request by ebaklund**
**Purpose**
Avoid crash caused by power management suspension where `fog` fails to translate domain state `pmsuspended`.

**Issues**
Closes #1472

**Changes**
- Changed the `driver.state()` function so that it does not crash on undefined domain state. Just return `nil` instead. The provider translates `nil` to `:unknown`.

### CODE REVIEW

File: lib/vagrant-libvirt/driver.rb [hunk 1]
```diff
@@ -135,7 +135,9 @@ def state(machine)
         end
 
         # TODO: terminated no longer appears to be a valid fog state, remove?
-        return :not_created if domain.nil? || domain.state.to_sym == :terminated
+        return :not_created if domain.nil?
+        return nil if domain.state.nil?
```
Comment (electrofelix) [inline lib/vagrant-libvirt/driver.rb:139]: While the provider code correctly handles nil, I do think it might be clearer to return `:unknown` here rather than rely on the subsequent conversion

Comment (electrofelix) [reply lib/vagrant-libvirt/driver.rb:139]: Looks like the unit tests need some adjustments as the expected state being passed in no longer matches in a few cases resulting in slightly different behaviour. Possibly also the tests are a little fragile in a couple of cases

Comment (ebaklund) [reply lib/vagrant-libvirt/driver.rb]: Thank you for feedback.
* I have translated the nil value to `:unknown` in the driver as requested.
* Added a unit test for nil handling.
* Made some unit tests less brittle with respect to domain.state call count.

**Comment by ebaklund** [comment]
Thank you for your feedback.
Ready for new review.
