### PR TITLE
Poweroff domain on `vagrant halt -f`

### LINKED ISSUE #1765: `vagrant halt -f` does not poweroff the domain if shutdown fails
**Describe the bug**
For some reason `vagrant halt -f` attempts to shutdown the domain (ACPI), and waits for the domain to shut itself down. If guest does not perform shutdown after ACPI, then vagrant-libvirt times out after 60 seconds and throws an exception.

**To Reproduce**
1. `vagrant up` a VM which does not respond to ACPI.
2. Attempt to poweroff the VM using `vagrant halt -f`.

**Expected behavior**
The domain is powered off immediately without sending ACPI.

**Screenshots**
n/a

**Versions (please complete the following information):**:
n/a

**Debug Log**
```
$ vagrant halt -f
==> default: Attempting direct shutdown of domain...
Traceback (most recent call last):
	68: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:248:in `<main>'
	67: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:301:in `cli'
	66: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/cli.rb:67:in `execute'
	65: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/plugins/commands/halt/command.rb:30:in `execute'
	64: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	63: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/plugin/v2/command.rb:232:in `each'
	62: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
	61: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/plugins/commands/halt/command.rb:31:in `block in execute'
	60: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/machine.rb:203:in `action'
	59: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/machine.rb:203:in `call'
	58: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:631:in `lock'
	57: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/machine.rb:217:in `block in action'
	56: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/machine.rb:248:in `action_raw'
	55: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `run'
	54: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/busy.rb:19:in `busy'
	53: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `block in run'
	52: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builder.rb:180:in `call'
	51: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	50: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	49: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	48: from /home/kantanavicius/.vagrant.d/gems/2.7.6/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/forward_ports.rb:202:in `call'
	47: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	46: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	45: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `run'
	44: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/busy.rb:19:in `busy'
	43: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `block in run'
	42: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builder.rb:180:in `call'
	41: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	40: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	39: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	38: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	37: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `run'
	36: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/busy.rb:19:in `busy'
	35: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `block in run'
	34: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builder.rb:180:in `call'
	33: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	32: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	31: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	30: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	29: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	28: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	27: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `run'
	26: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/busy.rb:19:in `busy'
	25: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `block in run'
	24: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builder.rb:180:in `call'
	23: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	22: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	21: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	20: from /home/kantanavicius/.vagrant.d/gems/2.7.6/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/shutdown_domain.rb:15:in `call'
	19: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	18: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	17: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `run'
	16: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/busy.rb:19:in `busy'
	15: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `block in run'
	14: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builder.rb:180:in `call'
	13: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	12: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	11: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	10: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builtin/call.rb:43:in `call'
	 9: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `run'
	 8: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/busy.rb:19:in `busy'
	 7: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `block in run'
	 6: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builder.rb:180:in `call'
	 5: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	 4: from /home/kantanavicius/.vagrant.d/gems/2.7.6/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/shutdown_domain.rb:61:in `call'
	 3: from /home/kantanavicius/.vagrant.d/gems/2.7.6/gems/fog-core-2.3.0/lib/fog/core/model.rb:72:in `wait_for'
	 2: from /home/kantanavicius/.vagrant.d/gems/2.7.6/gems/fog-core-2.3.0/lib/fog/core/wait_for.rb:6:in `wait_for'
	 1: from /home/kantanavicius/.vagrant.d/gems/2.7.6/gems/fog-core-2.3.0/lib/fog/core/wait_for.rb:6:in `loop'
/home/kantanavicius/.vagrant.d/gems/2.7.6/gems/fog-core-2.3.0/lib/fog/core/wait_for.rb:9:in `block in wait_for': The specified wait_for timeout (59.932046826 seconds) was exceeded (Fog::Errors::TimeoutError)
```

**A Vagrantfile to reproduce the issue:**
n/a

### PR DESCRIPTION
**Pull request by arg0d**
`vagrant halt -f` is supposed to poweroff the domain without attempting graceful shutdown. Before, `vagrant halt -f` was attempting to send ACPI and waiting for timeout before actually powering off the domain.

Fix a bug where ACPI timeout code would cause an exception to be thrown, instead of setting :result to false and proceeding to poweroff the domain.

The before behaviour:

`vagrant halt`:
    - attempt graceful shutdown (/sbin/shutdown)
        ERROR: next action
    - attempt sending ACPI (domain.shutdown)
        ERROR: timeout exception

`vagrant halt -f`:
    - attempt sending ACPI (domain.shutdown)
        ERROR: timeout exception

The after behaviour:

`vagrant halt`:
    - attempt graceful shutdown (/sbin/shutdown)
        ERROR: next action
    - attempt sending ACPI (domain.shutdown)
        ERROR: next action
    - poweroff the machine (domain.poweroff)
        ERROR: hopefully never

`vagrant halt -f`:
    - poweroff the machine (domain.poweroff)
        ERROR: hopefully never

Fixes #1765

### CODE REVIEW

**Comment by arg0d** [comment]
@electrofelix This is quote important for my use case, because VMs cannot be shut down if they are stuck/crashed.

File: lib/vagrant-libvirt/action/shutdown_domain.rb [hunk 1]
```diff
@@ -46,6 +46,8 @@ def call(env)
 
           return @app.call(env) if env[:result]
 
+          return @app.call(env) if env[:force_halt]
```
Comment (electrofelix) [inline lib/vagrant-libvirt/action/shutdown_domain.rb:49]: I'm inclined to think that checking `env[:force_halt]` should be done in the action.rb to call `HaltDomain` and next instead of handling this in ShutdownDomain, see adding the check at https://github.com/vagrant-libvirt/vagrant-libvirt/blob/06fa756b98f3a86254e3bd2cf2b17f2bd5829023/lib/vagrant-libvirt/action.rb#L197 and call `b3.use HaltDomain` followed by `next` instead.
